
/*
 * PNP IDs automatically generated from http://www.uefi.org/pnp_id_list
 * 
 * There is no charge for use of the specification itself. The promoters of
 * UEFI specifications have agreed that any IP needed to implement the
 * specification will be made available on reasonable and non-discriminatory
 * terms.
 *
 * This file was automatically generated on 2017-03-13 11:15:31
 * by https://github.com/golightlyb/PNP-ID
 *
 */

#include <stddef.h>  // size_t
#include <string.h> // memcmp

size_t num_ids = 2404;

/* pnp_keys is a string of 3-character PNP IDs */
static const char *pnp_keys =
"AAAAAEAAMAANAATABAABCABDABEABOABSABTABVACAACBACCACDACEACGACHACIACKACLACMACOACPACRACSACTACUACVADAADBADCADDADEADHADIADKADLADMADNADPADRADSADTADVADXADZAECAEDAEIAEJAEMAENAEPAETAFAAGCAGIAGLAGMAGOAGTAHCAHSAICAIEAIIAIKAILAIMAIRAISAIWAIXAJAAKBAKEAKIAKLAKMAKPAKYALAALCALDALEALGALHALIALJALKALLALMALNALOALPALRALSALTALVALXAMAAMBAMCAMDAMIAMLAMNAMOAMPAMRAMSAMTAMXANAANCANDANIANKANLANOANPANRANSANTANVANWANXAOAAOEAOLAOTAPCAPDAPEAPGAPIAPLAPMAPNAPPAPRAPSAPTAPVAPXARCARDAREARGARIARKARLARMAROARRARSARTASCASDASEASHASIASKASLASMASNASPASTASUASXASYATAATCATDATEATHATIATJATKATLATMATNATOATPATTATVATXAUGAUIAUOAURAUSAUTAUVAVAAVCAVDAVEAVGAVIAVJAVLAVMAVNAVOAVRAVTAVVAVXAWCAWLAWSAXBAXCAXEAXIAXLAXOAXPAXTAXXAXYAYDAYRAZHAZMAZTBACBANBBBBBHBBLBBXBCCBCDBCIBCMBCQBCSBDOBDRBDSBECBEIBEKBELBEOBFEBGBBGTBHZBIABICBIIBILBIOBITBLIBLNBLPBMDBMIBMLBMSBNEBNKBNOBNSBOBBOEBOIBOSBPDBPSBPUBRABRCBRGBRIBRMBROBSEBSGBSLBSNBSTBTCBTEBTFBTIBTOBUFBUGBUJBULBURBUSBUTBWKBXEBYDCAACACCAGCAICALCAMCANCARCASCATCAVCBICBRCBTCBXCCCCCICCJCCLCCPCDCCDDCDECDGCDICDKCDNCDPCDSCDTCDVCEACECCEDCEFCEICEMCENCEPCERCETCFGCGACGSCGTCHACHDCHECHGCHICHLCHMCHOCHPCHSCHTCHYCICCIICILCINCIPCIRCISCITCKCCKJCLACLDCLECLGCLICLMCLOCLTCLVCLXCMCCMDCMGCMICMMCMNCMOCMRCMSCMXCNBCNCCNECNICNNCNTCOBCODCOICOLCOMCONCOOCORCOSCOTCOWCOXCPCCPDCPICPLCPMCPPCPQCPTCPXCRACRCCRDCRECRHCRICRLCRNCROCRQCRSCRVCRXCSBCSCCSDCSECSICSLCSMCSOCSSCSTCTACTCCTECTLCTMCTNCTPCTRCTSCTXCUBCUKCVACVICVPCVSCWCCWRCXTCYBCYCCYDCYLCYPCYTCYVCYWCYXCZCCZEDACDAEDAIDAKDALDANDASDATDAUDAVDAWDAXDBDDBIDBKDBLDBNDCADCCDCDDCEDCIDCLDCMDCODCRDCSDCTDCVDDADDDDDEDDIDDSDDTDDVDECDEIDELDENDEXDFIDFKDFTDGADGCDGIDGKDGPDGSDGTDHDDHPDHQDHTDIADIGDIIDIMDINDISDITDJEDJPDKYDLBDLCDLGDLKDLLDLTDMBDMCDMMDMODMPDMSDMTDMVDNADNGDNIDNTDNVDOLDOMDONDOTDPADPCDPHDPIDPLDPMDPNDPSDPTDPXDQBDRBDRCDRDDRIDRSDSADSDDSIDSJDSMDSPDTADTCDTEDTIDTKDTLDTNDTODTTDTXDUADUNDVDDVLDVSDVTDWEDXCDXDDXLDXPDXSDYCDYMDYNDYXEAGEASEBHEBSEBTECAECCECHECIECKECLECMECOECPECSECTEDCEDGEDIEDMEDTEEEEEHEEPEESEGAEGDEGLEGNEGOEHJEHNEICEKAEKCEKSELAELCELEELGELIELLELMELOELSELTELUELXEMBEMCEMDEMEEMGEMIEMKEMOEMUENCENDENEENIENSENTEONEPCEPHEPIEPNEPSEQPEQXERGERIERNERPERSERTESAESBESCESDESGESIESKESLESNESSESTESYETCETDETHETIETKETLETSETTEUTEVEEVIEVXEXAEXCEXIEXNEXPEXREXTEXXEXYEYEEYFEZEEZPFANFARFBIFCBFCGFCSFDCFDDFDIFDTFECFELFENFERFFCFFIFGDFGLFHLFICFILFINFIRFISFITFJCFJSFJTFLEFLIFLYFMAFMCFMIFMLFMZFNCFNIFOAFOKFOSFOVFOXFPCFPEFPSFPXFRCFRDFREFRIFROFRSFSCFSIFSTFTCFTEFTGFTIFTLFTNFTRFTSFTWFUJFUNFUSFVCFVXFWAFWRFXXFZCFZIGACGAGGALGAUGCCGCIGCSGDCGDIGDSGDTGECGEDGEFGEHGEMGENGEOGERGESGETGFMGFNGGLGICGIMGIPGISGJNGLDGLEGLMGLSGMKGMLGMMGMNGMXGNDGNNGNZGOEGPRGRAGREGRHGRMGRVGRYGSBGSCGSMGSNGSTGSYGTCGTIGTKGTMGTSGTTGUDGUZGVCGVLGWIGWKGWYGZEHAEHAIHALHANHARHAYHCAHCEHCLHCMHCPHCWHDCHDIHDVHECHELHERHETHHCHHIHIBHICHIIHIKHILHIQHISHITHJIHKAHKCHKGHLGHMCHMKHMXHNSHOBHOEHOLHONHPAHPCHPDHPEHPIHPKHPNHPQHPRHRCHREHRIHRLHRSHRTHSCHSDHSMHSPHSTHTCHTIHTKHTLHTRHTXHUBHUKHUMHVRHWAHWCHWDHWPHXMHYCHYDHYLHYOHYPHYRHYTHYVIADIAFIAIIATIBCIBIIBMIBPIBRICAICCICDICEICIICMICNICOICPICSICVICXIDCIDEIDKIDNIDOIDPIDSIDTIDXIECIEEIEIIFSIFTIFXIFZIGCIGMIHEIICIIIIINIITIKEIKSILCILSIMAIMBIMCIMDIMEIMGIMIIMMIMNIMPIMTINAINCINDINEINFINGINIINKINLINMINNINOINPINSINTINVINXINZIOAIODIOMIONIOSIOTIPCIPDIPIIPMIPNIPPIPQIPRIPSIPTIPWIQIIQTIRDISAISCISGISIISLISMISPISRISSISTISYITAITCITDITEITIITKITLITMITNITPITRITSITTITXIUCIVIIVMIVRIVSIWRIWXIXDIXNJACJAEJASJATJAZJCEJDIJDLJENJETJFXJGDJICJKCJMTJPCJPWJQEJSDJSIJSKJTSJTYJUKJUPJVCJWDJWLJWSJWYKARKBIKBLKCDKCLKDEKDKKDMKDSKDTKECKEMKESKEUKEYKFCKFEKFXKGIKGLKIOKISKMCKMEKMLKMRKNCKNXKOBKODKOEKOLKOUKOWKPCKPTKRLKRMKRYKSCKSGKSLKSXKTCKTDKTEKTGKTIKTKKTNKURKVAKVXKWDKYCKYEKYKKYNKZIKZNLABLACLAFLAGLANLASLAVLBOLCCLCDLCELCILCMLCNLCSLCTLDNLDTLECLEDLEGLENLEOLEXLGCLGILGSLGXLHALHELHTLINLIPLITLJXLKMLLLLMGLMILMPLMTLNDLNKLNRLNTLNVLNXLOCLOELOGLOLLPELPILPLLSCLSDLSILSJLSLLSYLTCLTILTKLTNLTSLTVLTWLUCLUMLUXLVILWCLWRLWWLXCLXNLXSLZXMACMADMAEMAGMAIMALMANMASMATMAXMAYMAZMBCMBDMBMMBVMCAMCCMCDMCEMCGMCIMCLMCMMCNMCOMCPMCQMCRMCSMCTMCXMDAMDCMDDMDFMDGMDIMDKMDOMDRMDSMDTMDVMDXMDYMECMEDMEEMEGMEIMEJMEKMELMENMEPMEQMETMEUMEXMFGMFIMFRMGAMGCMGEMGLMGTMICMIDMIIMILMIMMINMIPMIRMISMITMIVMJIMJSMKCMKSMKTMKVMLDMLGMLIMLLMLMMLNMLPMLSMLTMLXMMAMMDMMFMMIMMMMMNMMSMNCMNIMNLMNPMODMOMMOSMOTMPCMPIMPJMPLMPNMPSMPXMQPMRAMRCMRDMRKMRLMROMRTMSAMSCMSDMSFMSGMSHMSIMSKMSLMSMMSPMSRMSTMSUMSVMSXMSYMTAMTBMTCMTDMTEMTHMTIMTJMTKMTLMTMMTNMTRMTSMTUMTXMUDMUKMVDMVIMVMMVNMVSMVXMWIMWRMWYMXDMXIMXLMXPMXTMXVMYAMYRMYXNACNADNAKNALNATNAVNAXNBLNBSNBTNCANCCNCENCINCLNCPNCRNCSNCTNDCNDFNDINDKNDLNDSNECNEONESNETNEUNEXNFCNFSNGCNGSNHTNICNISNITNIXNLCNMENMPNMSNMVNMXNNCNODNOENOINOKNORNOTNPANPINRLNRTNRVNSANSCNSINSPNSSNSTNTCNTINTLNTNNTRNTSNTTNTWNTXNUGNUINVCNVDNVINVLNVTNWCNWPNWSNXCNXGNXPNXQNXSNYCOAKOASOBSOCDOCNOCSODMODROECOEIOHWOICOIMOINOKIOLCOLDOLIOLTOLVOLYOMCOMNOMRONEONKONLONSONWONXOOSOPCOPIOPPOPTOPVOQIORGORIORNOSAOSDOSIOSPOSROTBOTIOTKOTMOTTOUKOVROWLOXUOYOOZCOZOPACPADPAKPAMPANPARPBIPBLPBNPBVPCAPCBPCCPCGPCIPCKPCLPCMPCOPCPPCSPCTPCWPCXPDMPDNPDRPDSPDTPDVPECPEGPEIPELPENPEPPERPETPFTPGIPGMPGPPGSPHCPHEPHIPHLPHOPHSPHYPICPIEPIMPIOPIXPJAPJDPJTPKAPLCPLFPLMPLTPLVPLXPLYPMCPMDPMMPMSPMTPMXPNGPNLPNPPNRPNSPNXPOLPONPORPOTPPCPPDPPIPPMPPPPPRPPXPQIPRAPRCPRDPRFPRGPRIPRMPROPRPPRSPRTPRXPSAPSCPSDPSEPSIPSLPSMPSTPSYPTAPTCPTGPTHPTIPTLPTSPTWPULPVCPVGPVIPVMPVNPVPPVRPXCPXEPXLPXMQCCQCHQCIQCKQCLQCPQDIQDMQDSQFFQFIQLCQQQQSIQTDQTHQTIQTMQTRQUAQUEQVURACRADRAIRANRARRASRATRAYRCERCHRCIRCNRCORDIRDMRDNRDSREARECREDREFREHRELREMRENRESRETREVREXRFIRFXRGBRGLRHDRHMRHTRICRIIRIORITRIVRJARJSRKCRLDRLNRMCRMPRMSRMTRNBROBROHROKROPROSRPIRPTRRIRSCRSHRSIRSNRSQRSRRSSRSVRSXRTCRTIRTKRTLRTSRUNRUPRVCRVIRVLRWCRXTRZSSAASAESAGSAISAKSAMSANSASSATSBCSBDSBISBSSBTSCBSCCSCDSCESCHSCISCLSCMSCNSCOSCPSCRSCSSCTSCXSDASDDSDESDFSDHSDISDKSDRSDSSDTSDXSEASEBSECSEESEGSEISELSEMSENSEOSEPSERSESSETSFMSFTSGCSGDSGESGISGLSGMSGOSGTSGWSGXSGZSHCSHGSHISHPSHRSHTSIASIBSICSIDSIESIGSIISILSIMSINSIRSISSITSIUSIXSJESKDSKMSKTSKYSLASLBSLCSLFSLHSLISLKSLMSLRSLSSLTSLXSMASMBSMCSMESMISMKSMLSMMSMOSMPSMRSMSSMTSNCSNISNKSNNSNOSNPSNSSNTSNWSNXSNYSOCSOISOLSONSORSOTSOYSPCSPESPHSPISPKSPLSPNSPRSPSSPTSPUSPXSQTSRCSRDSRFSRGSRSSRTSSCSSDSSESSISSJSSLSSPSSSSSTSTASTBSTCSTDSTESTFSTGSTHSTISTKSTLSTMSTNSTOSTPSTQSTRSTSSTTSTUSTWSTXSTYSUBSUMSUNSUPSURSVASVCSVDSVISVRSVSSVTSWCSWISWLSWOSWSSWTSXBSXDSXGSXLSXTSYCSYESYKSYLSYMSYNSYPSYSSYTSYVSYXSZMTAATABTAGTAITAMTASTATTAVTAXTBBTBCTBSTCCTCDTCETCFTCHTCITCJTCLTCMTCNTCOTCRTCSTCTTCXTDCTDDTDGTDMTDPTDSTDTTDVTDYTEATECTEKTELTERTETTEZTGCTGITGMTGSTGVTHNTICTILTIPTIVTIXTKCTKGTKNTKOTKSTLATLDTLETLFTLITLKTLLTLNTLSTLTTLVTLXTMCTMETMITMMTMRTMSTMTTMXTNCTNJTNMTNYTOETOGTOLTOMTONTOPTOSTOUTPCTPDTPETPJTPKTPRTPSTPTTPVTPZTRATRBTRCTRDTRETRITRLTRMTRNTRPTRSTRTTRUTRVTRXTSBTSCTSDTSETSFTSGTSHTSITSLTSPTSTTSVTSYTTATTBTTCTTETTITTKTTLTTPTTSTTXTTYTUATUTTVDTVITVLTVMTVOTVRTVSTVVTWATWETWHTWITWKTWXTXLTXNTXTTYNUASUBIUBLUBUUDNUECUEGUEIUETUFGUFOUHBUICUJRULTUMCUMGUMMUMTUNAUNBUNCUNDUNEUNFUNIUNMUNOUNPUNSUNTUNYUPPUPSURDUSAUSDUSEUSIUSRUTDUWCVADVAIVALVARVBRVBTVCCVCIVCJVCMVCXVDAVDCVDMVDOVDSVDTVECVEKVESVFIVHIVIAVIBVICVIDVIKVIMVINVIRVISVITVIZVLBVLCVLKVLTVLVVMIVMLVMWVNCVOBVPIVPRVPXVQ@VRCVRMVSCVSDVSIVSNVSPVSRVTBVTCVTGVTIVTKVTLVTMVTNVTSVTVVTXVUTVWBWACWALWANWAVWBNWBSWCIWCSWDCWDEWEBWECWELWEYWHIWIIWILWINWIPWKHWLDWMLWMOWMTWNIWNVWNXWPAWPIWRCWSCWSPWSTWTCWTIWTKWTSWVMWVVWWPWWVWXTWYSWYTXACXADXDMXERXFGXFOXINXIOXIRXITXLXXMMXNTXOCXQUXRCXROXSNXSTXSYXTDXTEXTLXTNXYCXYEYEDYHQYHWYMHYOWZANZAXZAZZBRZBXZCTZDSZENZGTZICZMCZMTZMZZNIZNXZOWZRNZSEZTCZTEZTIZTMZTTZWEZYDZYPZYTZYXZZZinu";

/* pnp_names is an array of strings of company names, eaching
 * matching pnp_keys in order. */
static const char *pnp_names[] =
{
"Avolites Ltd",
"Anatek Electronics Inc.",
"Aava Mobile Oy",
"AAEON Technology Inc.",
"Ann Arbor Technologies",
"ABBAHOME INC.",
"AboCom System Inc.",
"Allen Bradley Company",
"Alcatel Bell",
"D-Link Systems Inc",
"Abaco Systems, Inc.",
"Anchor Bay Technologies, Inc.",
"Advanced Research Technology",
"Ariel Corporation",
"Aculab Ltd",
"Accton Technology Corporation",
"AWETA BV",
"Actek Engineering Pty Ltd",
"A&R Cambridge Ltd.",
"Archtek Telecom Corporation",
"Ancor Communications Inc",
"Acksys",
"Apricot Computers",
"Acroloop Motion Control Systems Inc",
"Allion Computer Inc.",
"Aspen Tech Inc",
"Acer Technologies",
"Altos Computer Systems",
"Applied Creative Technology",
"Acculogic",
"ActivCard S.A",
"Addi-Data GmbH",
"Aldebbaron",
"Acnhor Datacomm",
"Advanced Peripheral Devices Inc",
"Arithmos, Inc.",
"Aerodata Holdings Ltd",
"ADI Systems Inc",
"Adtek System Science Company Ltd",
"ASTRA Security Products Ltd",
"Ad Lib MultiMedia Inc",
"Analog & Digital Devices Tel. Inc",
"Adaptec Inc",
"Nasa Ames Research Center",
"Analog Devices Inc",
"Adtek",
"Advanced Micro Devices Inc",
"Adax Inc",
"ADDER TECHNOLOGY LTD",
"Antex Electronics Corporation",
"Advanced Electronic Designs, Inc.",
"Actiontec Electric Inc",
"Alpha Electronics Company",
"ASEM S.p.A.",
"Avencall",
"Aetas Peripheral International",
"Aethra Telecomunicazioni S.r.l.",
"Alfa Inc",
"Beijing Aerospace Golden Card Electronic Engineering Co.,Ltd.",
"Artish Graphics Inc",
"Argolis",
"Advan Int'l Corporation",
"AlgolTek, Inc.",
"Agilent Technologies",
"Advantech Co., Ltd.",
"Beijing AnHeng SecoTech Information Technology Co., Ltd.",
"Arnos Insturments & Computer Systems",
"Altmann Industrieelektronik",
"Amptron International Inc.",
"Dongguan Alllike Electronics Co., Ltd.",
"Altos India Ltd",
"AIMS Lab Inc",
"Advanced Integ. Research Inc",
"Alien Internet Services",
"Aiwa Company Ltd",
"ALTINEX, INC.",
"AJA Video Systems, Inc.",
"Akebia Ltd",
"AKAMI Electric Co.,Ltd",
"AKIA Corporation",
"AMiT Ltd",
"Asahi Kasei Microsystems Company Ltd",
"Atom Komplex Prylad",
"Askey Computer Corporation",
"Alacron Inc",
"Altec Corporation",
"In4S Inc",
"Alenco BV",
"Realtek Semiconductor Corp.",
"AL Systems",
"Acer Labs",
"Altec Lansing",
"Acrolink Inc",
"Alliance Semiconductor Corporation",
"Acutec Ltd.",
"Alana Technologies",
"Algolith Inc.",
"Alps Electric Company Ltd",
"Advanced Logic",
"Avance Logic Inc",
"Altra",
"AlphaView LCD",
"ALEXON Co.,Ltd.",
"Asia Microelectronic Development Inc",
"Ambient Technologies, Inc.",
"Attachmate Corporation",
"Amdek Corporation",
"American Megatrends Inc",
"Anderson Multimedia Communications (HK) Limited",
"Amimon LTD.",
"Amino Technologies PLC and Amino Communications Limited",
"AMP Inc",
"AmTRAN Technology Co., Ltd.",
"ARMSTEL, Inc.",
"AMT International Industry",
"AMX LLC",
"Anakron",
"Ancot",
"Adtran Inc",
"Anigma Inc",
"Anko Electronic Company Ltd",
"Analogix Semiconductor, Inc",
"Anorad Corporation",
"Andrew Network Production",
"ANR Ltd",
"Ansel Communication Company",
"Ace CAD Enterprise Company Ltd",
"Beijing ANTVR Technology Co., Ltd.",
"Analog Way SAS",
"Acer Netxus Inc",
"AOpen Inc.",
"Advanced Optics Electronics, Inc.",
"America OnLine",
"Alcatel",
"American Power Conversion",
"AppliAdata",
"Alpine Electronics, Inc.",
"Horner Electric Inc",
"A Plus Info Corporation",
"Aplicom Oy",
"Applied Memory Tech",
"Appian Tech Inc",
"Apple Computer Inc",
"Aprilia s.p.a.",
"Autologic Inc",
"Audio Processing Technology Ltd",
"A+V Link",
"AP Designs Ltd",
"Alta Research Corporation",
"AREC Inc.",
"ICET S.p.A.",
"Argus Electronics Co., LTD",
"Argosy Research Inc",
"Ark Logic Inc",
"Arlotto Comnet Inc",
"Arima",
"Poso International B.V.",
"ARRIS Group, Inc.",
"Arescom Inc",
"Corion Industrial Corporation",
"Ascom Strategic Technology Unit",
"USC Information Sciences Institute",
"AseV Display Labs",
"Ashton Bentley Concepts",
"Ahead Systems",
"Ask A/S",
"AccuScene Corporation Ltd",
"ASEM S.p.A.",
"Asante Tech Inc",
"ASP Microelectronics Ltd",
"AST Research Inc",
"Asuscom Network Inc",
"AudioScience",
"Rockwell Collins / Airshow Systems",
"Allied Telesyn International (Asia) Pte Ltd",
"Ably-Tech Corporation",
"Alpha Telecom Inc",
"Innovate Ltd",
"Athena Informatica S.R.L.",
"Allied Telesis KK",
"ArchiTek Corporation",
"Allied Telesyn Int'l",
"Arcus Technology Ltd",
"ATM Ltd",
"Athena Smartcard Solutions Ltd.",
"ASTRO DESIGN, INC.",
"Alpha-Top Corporation",
"AT&T",
"Office Depot, Inc.",
"Athenix Corporation",
"August Home, Inc.",
"Alps Electric Inc",
"DO NOT USE - AUO",
"Aureal Semiconductor",
"ASUSTek COMPUTER INC",
"Autotime Corporation",
"Auvidea GmbH",
"Avaya Communication",
"Auravision Corporation",
"Avid Electronics Corporation",
"Add Value Enterpises (Asia) Pte Ltd",
"Avegant Corporation",
"Nippon Avionics Co.,Ltd",
"Atelier Vision Corporation",
"Avalue Technology Inc.",
"AVM GmbH",
"Advance Computer Corporation",
"Avocent Corporation",
"AVer Information Inc.",
"Avtek (Electronics) Pty Ltd",
"SBS Technologies (Canada), Inc. (was Avvida Systems, Inc.)",
"A/Vaux Electronics",
"Access Works Comm Inc",
"Aironet Wireless Communications, Inc",
"Wave Systems",
"Adrienne Electronics Corporation",
"AXIOMTEK CO., LTD.",
"Axell Corporation",
"American Magnetics",
"Axel",
"Axonic Labs LLC",
"American Express",
"Axtend Technologies Inc",
"Axxon Computer Corporation",
"AXYZ Automation Services, Inc",
"Aydin Displays",
"Airlib, Inc",
"Shenzhen three Connaught Information Technology Co., Ltd. (3nod Group)",
"AZ Middelheim - Radiotherapy",
"Aztech Systems Ltd",
"Biometric Access Corporation",
"Banyan",
"an-najah university",
"B&Bh",
"Brain Boxes Limited",
"Black Box Corporation",
"Beaver Computer Corporaton",
"Barco GmbH",
"Broadata Communications Inc.",
"Broadcom",
"Deutsche Telekom Berkom GmbH",
"Booria CAD/CAM systems",
"Brahler ICS",
"Blonder Tongue Labs, Inc.",
"Barco Display Systems",
"Beckhoff Automation",
"Beckworth Enterprises Inc",
"Beko Elektronik A.S.",
"Beltronic Industrieelektronik GmbH",
"Baug & Olufsen",
"B.F. Engineering Corporation",
"Barco Graphics N.V",
"Budzetron Inc",
"BitHeadz, Inc.",
"Biamp Systems Corporation",
"Big Island Communications",
"Boeckeler Instruments Inc",
"Billion Electric Company Ltd",
"BioLink Technologies International, Inc.",
"Bit 3 Computer",
"Busicom",
"BioLink Technologies",
"Bloomberg L.P.",
"Blackmagic Design",
"Benson Medical Instruments Company",
"BIOMED Lab",
"BIOMEDISYS",
"Bull AB",
"Banksia Tech Pty Ltd",
"Bang & Olufsen",
"Boulder Nonlinear Systems",
"Rainy Orchard",
"BOE",
"NINGBO BOIGLE DIGITAL TECHNOLOGY CO.,LTD",
"BOS",
"Micro Solutions, Inc.",
"Barco, N.V.",
"Best Power",
"Braemac Pty Ltd",
"BARC",
"Bridge Information Co., Ltd",
"Boca Research Inc",
"Braemar Inc",
"BROTHER INDUSTRIES,LTD.",
"Bose Corporation",
"Robert Bosch GmbH",
"Biomedical Systems Laboratory",
"BRIGHTSIGN, LLC",
"BodySound Technologies, Inc.",
"Bit 3 Computer",
"Brilliant Technology",
"Bitfield Oy",
"BusTech Inc",
"BioTao Ltd",
"Yasuhiko Shirai Melco Inc",
"B.U.G., Inc.",
"ATI Tech Inc",
"Bull",
"Bernecker & Rainer Ind-Eletronik GmbH",
"BusTek",
"21ST CENTURY ENTERTAINMENT",
"Bitworks Inc.",
"Buxco Electronics",
"byd:sign corporation",
"Castles Automation Co., Ltd",
"CA & F Elettronica",
"CalComp",
"Canon Inc.",
"Acon",
"Cambridge Audio",
"Canopus Company Ltd",
"Cardinal Company Ltd",
"CASIO COMPUTER CO.,LTD",
"Consultancy in Advanced Technology",
"Cavium Networks, Inc",
"ComputerBoards Inc",
"Cebra Tech A/S",
"Cabletime Ltd",
"Cybex Computer Products Corporation",
"C-Cube Microsystems",
"Cache",
"CONTEC CO.,LTD.",
"CCL/ITRI",
"Capetronic USA Inc",
"Core Dynamics Corporation",
"Convergent Data Devices",
"Colin.de",
"Christie Digital Systems Inc",
"Concept Development Inc",
"Cray Communications",
"Codenoll Technical Corporation",
"CalComp",
"Computer Diagnostic Systems",
"IBM Corporation",
"Convergent Design Inc.",
"Consumer Electronics Association",
"Chicony Electronics Company Ltd",
"Cambridge Electronic Design Ltd",
"Cefar Digital Vision",
"Crestron Electronics, Inc.",
"MEC Electronics GmbH",
"Centurion Technologies P/L",
"C-DAC",
"Ceronix",
"TEC CORPORATION",
"Atlantis",
"Chunghwa Picture Tubes, LTD",
"Chyron Corp",
"congatec AG",
"Chase Research PLC",
"ChangHong Electric Co.,Ltd",
"Acer Inc",
"Sichuan Changhong Electric CO, LTD.",
"Chrontel Inc",
"Chloride-R&D",
"CHIC TECHNOLOGY CORP.",
"Sichuang Changhong Corporation",
"CH Products",
"Agentur Chairos",
"Chunghwa Picture Tubes,LTD.",
"Cherry GmbH",
"Comm. Intelligence Corporation",
"Cromack Industries Inc",
"Citicom Infotech Private Limited",
"Citron GmbH",
"Ciprico Inc",
"Cirrus Logic Inc",
"Cisco Systems Inc",
"Citifax Limited",
"The Concept Keyboard Company Ltd",
"Carina System Co., Ltd.",
"Clarion Company Ltd",
"COMMAT L.t.d.",
"Classe Audio",
"CoreLogic",
"Cirrus Logic Inc",
"CrystaLake Multimedia",
"Clone Computers",
"automated computer control systems",
"Clevo Company",
"CardLogix",
"CMC Ltd",
"Colorado MicroDisplay, Inc.",
"Chenming Mold Ind. Corp.",
"C-Media Electronics",
"Comtime GmbH",
"Chimei Innolux Corporation",
"Chi Mei Optoelectronics corp.",
"Cambridge Research Systems Ltd",
"CompuMaster Srl",
"Comex Electronics AB",
"American Power Conversion",
"Alvedon Computers Ltd",
"Cine-tal",
"Connect Int'l A/S",
"Canon Inc",
"COINT Multimedia Systems",
"COBY Electronics Co., Ltd",
"CODAN Pty. Ltd.",
"Codec Inc.",
"Rockwell Collins, Inc.",
"Comtrol Corporation",
"Contec Company Ltd",
"coolux GmbH",
"Corollary Inc",
"CoStar Corporation",
"Core Technology Inc",
"Polycow Productions",
"Comrex",
"Ciprico Inc",
"CompuAdd",
"Computer Peripherals Inc",
"Compal Electronics Inc",
"Capella Microsystems Inc.",
"Compound Photonics",
"Compaq Computer Company",
"cPATH",
"Powermatic Data Systems",
"CRALTECH ELECTRONICA, S.L.",
"CONRAC GmbH",
"Cardinal Technical Inc",
"Creative Labs Inc",
"Contemporary Research Corp.",
"Crio Inc.",
"Creative Logic",
"Cornerstone Imaging",
"Extraordinary Technologies PTY Limited",
"Cirque Corporation",
"Crescendo Communication Inc",
"Cerevo Inc.",
"Cyrix Corporation",
"Transtex SA",
"Crystal Semiconductor",
"Cresta Systems Inc",
"Concept Solutions & Engineering",
"Cabletron System Inc",
"Cloudium Systems Ltd.",
"Cosmic Engineering Inc.",
"California Institute of Technology",
"CSS Laboratories",
"CSTI Inc",
"CoSystems Inc",
"CTC Communication Development Company Ltd",
"Chunghwa Telecom Co., Ltd.",
"Creative Technology Ltd",
"Computerm Corporation",
"Computone Products",
"Computer Technology Corporation",
"Control4 Corporation",
"Comtec Systems Co., Ltd.",
"Creatix Polymedia GmbH",
"Cubix Corporation",
"Calibre UK Ltd",
"Covia Inc.",
"Colorado Video, Inc.",
"Chromatec Video Products Ltd",
"Clarity Visual Systems",
"Curtiss-Wright Controls, Inc.",
"Connectware Inc",
"Conexant Systems",
"CyberVision",
"Cylink Corporation",
"Cyclades Corporation",
"Cyberlabs",
"CYPRESS SEMICONDUCTOR CORPORATION",
"Cytechinfo Inc",
"Cyviz AS",
"Cyberware",
"Cyrix Corporation",
"Shenzhen ChuangZhiCheng Technology Co., Ltd.",
"Carl Zeiss AG",
"Digital Acoustics Corporation",
"Digatron Industrie Elektronik GmbH",
"DAIS SET Ltd.",
"Daktronics",
"Digital Audio Labs Inc",
"Danelec Marine A/S",
"DAVIS AS",
"Datel Inc",
"Daou Tech Inc",
"Davicom Semiconductor Inc",
"DA2 Technologies Inc",
"Data Apex Ltd",
"Diebold Inc.",
"DigiBoard Inc",
"Databook Inc",
"Doble Engineering Company",
"DB Networks Inc",
"Digital Communications Association",
"Dale Computer Corporation",
"Datacast LLC",
"dSPACE GmbH",
"Concepts Inc",
"Dynamic Controls Ltd",
"DCM Data Products",
"Dialogue Technology Corporation",
"Decros Ltd",
"Diamond Computer Systems Inc",
"Dancall Telecom A/S",
"Datatronics Technology Inc",
"DA2 Technologies Corporation",
"Danka Data Devices",
"Datasat Digital Entertainment",
"Data Display AG",
"Barco, N.V.",
"Datadesk Technologies Inc",
"Delta Information Systems, Inc",
"Digital Equipment Corporation",
"Deico Electronics",
"Dell Inc.",
"Densitron Computers Ltd",
"idex displays",
"DFI",
"SharkTec A/S",
"DEI Holdings dba Definitive Technology",
"Digiital Arts Inc",
"Data General Corporation",
"DIGI International",
"DugoTech Co., LTD",
"Digicorp European sales S.A.",
"Diagsoft Inc",
"Dearborn Group Technology",
"Dension Audio Systems",
"DH Print",
"Quadram",
"Projectavision Inc",
"Diadem",
"Digicom S.p.A.",
"Dataq Instruments Inc",
"dPict Imaging, Inc.",
"Daintelecom Co., Ltd",
"Diseda S.A.",
"Dragon Information Technology",
"Capstone Visua lProduct Development",
"Maygay Machines, Ltd",
"Datakey Inc",
"Dolby Laboratories Inc.",
"Diamond Lane Comm. Corporation",
"Digital-Logic GmbH",
"D-Link Systems Inc",
"Dell Inc",
"Digitelec Informatique Park Cadera",
"Digicom Systems Inc",
"Dune Microsystems Corporation",
"Dimond Multimedia Systems Inc",
"Data Modul AG",
"D&M Holdings Inc, Professional Business Company",
"DOME imaging systems",
"Distributed Management Task Force, Inc. (DMTF)",
"NDS Ltd",
"DNA Enterprises, Inc.",
"Apache Micro Peripherals Inc",
"Deterministic Networks Inc.",
"Dr. Neuhous Telekommunikation GmbH",
"DiCon",
"Dolman Technologies Group Inc",
"Dome Imaging Systems",
"DENON, Ltd.",
"Dotronic Mikroelektronik GmbH",
"DigiTalk Pro AV",
"Delta Electronics Inc",
"Delphi Automotive LLP",
"DocuPoint",
"Digital Projection Limited",
"ADPM Synthesis sas",
"Shanghai Lexiang Technology Limited",
"Digital Processing Systems",
"DPT",
"DpiX, Inc.",
"Datacube Inc",
"Dr. Bott KG",
"Data Ray Corp.",
"DIGITAL REFLECTION INC.",
"Data Race Inc",
"DRS Defense Solutions, LLC",
"Display Solution AG",
"DS Multimedia Pte Ltd",
"Digitan Systems Inc",
"VR Technology Holdings Limited",
"DSM Digital Services GmbH",
"Domain Technology Inc",
"DELTATEC",
"DTC Tech Corporation",
"Dimension Technologies, Inc.",
"Diversified Technology, Inc.",
"Dynax Electronics (HK) Ltd",
"e-Net Inc",
"Datang Telephone Co",
"Deutsche Thomson OHG",
"Design & Test Technology, Inc.",
"Data Translation",
"Dosch & Amand GmbH & Company KG",
"NCR Corporation",
"Dictaphone Corporation",
"Devolo AG",
"Digital Video System",
"Data Video",
"Daewoo Electronics Company Ltd",
"Digipronix Control Systems",
"DECIMATOR DESIGN PTY LTD",
"Dextera Labs Inc",
"Data Expert Corporation",
"Signet",
"Dycam Inc",
"Dymo-CoStar Corporation",
"Askey Computer Corporation",
"Dynax Electronics (HK) Ltd",
"ELTEC Elektronik AG",
"Evans and Sutherland Computer",
"Data Price Informatica",
"EBS Euchner Büro- und Schulsysteme GmbH",
"HUALONG TECHNOLOGY CO., LTD",
"Electro Cam Corp.",
"ESSential Comm. Corporation",
"EchoStar Corporation",
"Enciris Technologies",
"Eugene Chukhlomin Sole Proprietorship, d.b.a.",
"Excel Company Ltd",
"E-Cmos Tech Corporation",
"Echo Speech Corporation",
"Elecom Company Ltd",
"Elitegroup Computer Systems Company Ltd",
"Enciris Technologies",
"e.Digital Corporation",
"Electronic-Design GmbH",
"Edimax Tech. Company Ltd",
"EDMI",
"Emerging Display Technologies Corp",
"ET&T Technology Company Ltd",
"EEH Datalink GmbH",
"E.E.P.D. GmbH",
"EE Solutions, Inc.",
"Elgato Systems LLC",
"EIZO GmbH Display Technologies",
"Eagle Technology",
"Egenera, Inc.",
"Ergo Electronics",
"Epson Research",
"Enhansoft",
"Eicon Technology Corporation",
"MagTek Inc.",
"Eastman Kodak Company",
"EKSEN YAZILIM",
"ELAD srl",
"Electro Scientific Ind",
"Elecom Company Ltd",
"Elmeg GmbH Kommunikationstechnik",
"Edsun Laboratories",
"Electrosonic Ltd",
"Elmic Systems Inc",
"Elo TouchSystems Inc",
"ELSA GmbH",
"Element Labs, Inc.",
"Express Industrial, Ltd.",
"Elonex PLC",
"Embedded computing inc ltd",
"eMicro Corporation",
"Embrionix Design Inc.",
"EMiNE TECHNOLOGY COMPANY, LTD.",
"EMG Consultants Inc",
"Ex Machina Inc",
"Emcore Corporation",
"ELMO COMPANY, LIMITED",
"Emulex Corporation",
"Eizo Nanao Corporation",
"ENIDAN Technologies Ltd",
"ENE Technology Inc.",
"Efficient Networks",
"Ensoniq Corporation",
"Enterprise Comm. & Computing Inc",
"Eon Instrumentation, Inc.",
"Empac",
"Epiphan Systems Inc.",
"Envision Peripherals, Inc",
"EPiCON Inc.",
"KEPS",
"Equipe Electronics Ltd.",
"Equinox Systems Inc",
"Ergo System",
"Ericsson Mobile Communications AB",
"Ericsson, Inc.",
"Euraplan GmbH",
"Eizo Rugged Solutions",
"Escort Insturments Corporation",
"Elbit Systems of America",
"Esterline Belgium BVBA",
"Eden Sistemas de Computacao S/A",
"Ensemble Designs, Inc",
"ELCON Systemtechnik GmbH",
"Extended Systems, Inc.",
"ES&S",
"Esterline Technologies",
"eSATURNUS",
"ESS Technology Inc",
"Embedded Solution Technology",
"E-Systems Inc",
"Everton Technology Company Ltd",
"ELAN MICROELECTRONICS CORPORATION",
"Etherboot Project",
"Eclipse Tech Inc",
"eTEK Labs Inc.",
"Evertz Microsystems Ltd.",
"Electronic Trade Solutions Ltd",
"E-Tech Inc",
"Ericsson Mobile Networks B.V.",
"Advanced Micro Peripherals Ltd",
"eviateg GmbH",
"Everex",
"Exabyte",
"Excession Audio",
"Exide Electronics",
"RGB Systems, Inc. dba Extron Electronics",
"Data Export Corporation",
"Explorer Inc.",
"Exatech Computadores & Servicos Ltda",
"Exxact GmbH",
"Exterity Ltd",
"eyevis GmbH",
"eyefactive Gmbh",
"EzE Technologies",
"Storm Technology",
"Fantalooks Co., Ltd.",
"Farallon Computing",
"Interface Corporation",
"Furukawa Electric Company Ltd",
"First International Computer Ltd",
"Focus Enhancements, Inc.",
"Future Domain",
"Forth Dimension Displays Ltd",
"Future Designs, Inc.",
"Fujitsu Display Technologies Corp.",
"FURUNO ELECTRIC CO., LTD.",
"Fellowes & Questec",
"Fen Systems Ltd.",
"Ferranti Int'L",
"FUJIFILM Corporation",
"Fairfield Industries",
"Lisa Draexlmaier GmbH",
"Fujitsu General Limited.",
"FHLP",
"Formosa Industrial Computing Inc",
"Forefront Int'l Ltd",
"Finecom Co., Ltd.",
"Chaplet Systems Inc",
"FLY-IT Simulators",
"Feature Integration Technology Inc.",
"Fujitsu Takamisawa Component Limited",
"Fujitsu Spain",
"F.J. Tieman BV",
"ADTI Media, Inc",
"Faroudja Laboratories",
"Butterfly Communications",
"Fast Multimedia AG",
"Ford Microelectronics Inc",
"Fellowes, Inc.",
"Fujitsu Microelect Ltd",
"Formoza-Altair",
"Fanuc LTD",
"Funai Electric Co., Ltd.",
"FOR-A Company Limited",
"Fokus Technologies GmbH",
"Foss Tecator",
"FOVE INC",
"HON HAI PRECISON IND.CO.,LTD.",
"Fingerprint Cards AB",
"Fujitsu Peripherals Ltd",
"Deltec Corporation",
"Cirel Systemes",
"Force Computers",
"Freedom Scientific BLV",
"Forvus Research Inc",
"Fibernet Research Inc",
"FARO Technologies",
"South Mountain Technologies, LTD",
"Future Systems Consulting KK",
"Fore Systems Inc",
"Modesto PC Inc",
"Futuretouch Corporation",
"Frontline Test Equipment Inc.",
"FTG Data Systems",
"FastPoint Technologies, Inc.",
"FUJITSU TEN LIMITED",
"Fountain Technologies Inc",
"Mediasonic",
"FocalTech Systems Co., Ltd.",
"MindTribe Product Engineering, Inc.",
"Fujitsu Ltd",
"sisel muhendislik",
"Fujitsu Siemens Computers GmbH",
"First Virtual Corporation",
"C-C-C Group Plc",
"Attero Tech, LLC",
"Flat Connections Inc",
"Fuji Xerox",
"Founder Group Shenzhen Co.",
"FZI Forschungszentrum Informatik",
"GreenArrays, Inc.",
"Gage Applied Sciences Inc",
"Galil Motion Control",
"Gaudi Co., Ltd.",
"GCC Technologies Inc",
"Gateway Comm. Inc",
"Grey Cell Systems Ltd",
"General Datacom",
"G. Diehl ISDN GmbH",
"GDS",
"Vortex Computersysteme GmbH",
"Gechic Corporation",
"General Dynamics C4 Systems",
"GE Fanuc Embedded Systems",
"Abaco Systems, Inc.",
"Gem Plus",
"Genesys ATE Inc",
"GEO Sense",
"GERMANEERS GmbH",
"GES Singapore Pte Ltd",
"Getac Technology Corporation",
"GFMesstechnik GmbH",
"Gefen Inc.",
"Google Inc.",
"General Inst. Corporation",
"Guillemont International",
"GI Provision Ltd",
"AT&T Global Info Solutions",
"Grand Junction Networks",
"Goldmund - Digital Audio SA",
"AD electronics",
"Genesys Logic",
"Gadget Labs LLC",
"GMK Electronic Design GmbH",
"General Information Systems",
"GMM Research Inc",
"GEMINI 2000 Ltd",
"GMX Inc",
"Gennum Corporation",
"GN Nettest Inc",
"Gunze Ltd",
"GOEPEL electronic GmbH",
"GoPro, Inc.",
"Graphica Computer",
"GOLD RAIN ENTERPRISES CORP.",
"Granch Ltd",
"Garmin International",
"Advanced Gravis",
"Robert Gray Company",
"NIPPONDENCHI CO,.LTD",
"General Standards Corporation",
"Goldstar Company Ltd",
"Grandstream Networks, Inc.",
"Graphic SystemTechnology",
"Grossenbacher Systeme AG",
"Graphtec Corporation",
"Goldtouch",
"G-Tech Corporation",
"Garnet System Company Ltd",
"Geotest Marvin Test Systems Inc",
"General Touch Technology Co., Ltd.",
"Guntermann & Drunck GmbH",
"Guzik Technical Enterprises",
"GVC Corporation",
"Global Village Communication",
"GW Instruments",
"Gateworks Corporation",
"Gateway 2000",
"GUNZE Limited",
"Haider electronics",
"Haivision Systems Inc.",
"Halberthal",
"Hanchang System Corporation",
"Harris Corporation",
"Hayes Microcomputer Products Inc",
"DAT",
"Hitachi Consumer Electronics Co., Ltd",
"HCL America Inc",
"HCL Peripherals",
"Hitachi Computer Products Inc",
"Hauppauge Computer Works Inc",
"HardCom Elektronik & Datateknik",
"HD-INFO d.o.o.",
"Holografika kft.",
"Hisense Electric Co., Ltd.",
"Hitachi Micro Systems Europe Ltd",
"Ascom Business Systems",
"HETEC Datensysteme GmbH",
"HIRAKAWA HEWTECH CORP.",
"Fraunhofer Heinrich-Hertz-Institute",
"Hibino Corporation",
"Hitachi Information Technology Co., Ltd.",
"Harman International Industries, Inc",
"Hikom Co., Ltd.",
"Hilevel Technology",
"Kaohsiung Opto Electronics Americas, Inc.",
"Hope Industrial Systems, Inc.",
"Hitachi America Ltd",
"Harris & Jeffries Inc",
"HONKO MFG. CO., LTD.",
"HKC OVERSEAS LIMITED",
"Josef Heim KG",
"China Hualu Group Co., Ltd.",
"Hualon Microelectric Corporation",
"hmk Daten-System-Technik BmbH",
"HUMAX Co., Ltd.",
"Hughes Network Systems",
"HOB Electronic GmbH",
"Hosiden Corporation",
"Holoeye Photonics AG",
"Sonitronix",
"Zytor Communications",
"Hewlett-Packard Co.",
"Hewlett Packard",
"Hewlett Packard Enterprise",
"Headplay, Inc.",
"HAMAMATSU PHOTONICS K.K.",
"HP Inc.",
"Hewlett-Packard Co.",
"H.P.R. Electronics GmbH",
"Hercules",
"Qingdao Haier Electronics Co., Ltd.",
"Hall Research",
"Herolab GmbH",
"Harris Semiconductor",
"HERCULES",
"Hagiwara Sys-Com Company Ltd",
"HannStar Display Corp",
"AT&T Microelectronics",
"HannStar Display Corp",
"Horsent Technology Co., Ltd.",
"Hitachi Ltd",
"Hampshire Company, Inc.",
"Holtek Microelectronics Inc",
"HTBLuVA Mödling",
"Shenzhen ZhuoYi HengTong Computer Technology Limited",
"Hitex Systementwicklung GmbH",
"GAI-Tronics, A Hubbell Company",
"Hoffmann + Krippner GmbH",
"IMP Electronics Ltd.",
"HTC Corportation",
"Harris Canada Inc",
"DBA Hans Wedemeyer",
"Highwater Designs Ltd",
"Hewlett Packard",
"Hexium Ltd.",
"Hypercope Gmbh Aachen",
"Hydis Technologies.Co.,LTD",
"Shanghai Chai Ming Huang Info&Tech Co, Ltd",
"HYC CO., LTD.",
"Hyphen Ltd",
"Hypertec Pty Ltd",
"Heng Yu Technology (HK) Limited",
"Hynix Semiconductor",
"IAdea Corporation",
"Institut f r angewandte Funksystemtechnik GmbH",
"Integration Associates, Inc.",
"IAT Germany GmbH",
"Integrated Business Systems",
"INBINE.CO.LTD",
"IBM Brasil",
"IBP Instruments GmbH",
"IBR GmbH",
"ICA Inc",
"BICC Data Networks Ltd",
"ICD Inc",
"IC Ensemble",
"Infotek Communication Inc",
"Intracom SA",
"Sanyo Icon",
"Intel Corp",
"ICP Electronics, Inc./iEi Technology Corp.",
"Integrated Circuit Systems",
"Inside Contactless",
"ICCC A/S",
"International Datacasting Corporation",
"IDE Associates",
"IDK Corporation",
"Idneo Technologies",
"IDEO Product Development",
"Integrated Device Technology, Inc.",
"Interdigital Sistemas de Informacao",
"International Display Technology",
"IDEXX Labs",
"Interlace Engineering Corporation",
"IEE",
"Interlink Electronics",
"In Focus Systems Inc",
"Informtech",
"Infineon Technologies AG",
"Infinite Z",
"Intergate Pty Ltd",
"IGM Communi",
"InHand Electronics",
"ISIC Innoscan Industrial Computers A/S",
"Intelligent Instrumentation",
"IINFRA Co., Ltd",
"Informatik Information Technologies",
"Ikegami Tsushinki Co. Ltd.",
"Ikos Systems Inc",
"Image Logic Corporation",
"Innotech Corporation",
"Imagraph",
"ART s.r.l.",
"IMC Networks",
"ImasDe Canarias S.A.",
"Imagraph",
"IMAGENICS Co., Ltd.",
"International Microsystems Inc",
"Immersion Corporation",
"Impossible Production",
"Impinj",
"Inmax Technology Corporation",
"Inventec Corporation",
"Home Row Inc",
"ILC",
"Inventec Electronics (M) Sdn. Bhd.",
"Inframetrics Inc",
"Integraph Corporation",
"Initio Corporation",
"Indtek Co., Ltd.",
"InnoLux Display Corporation",
"InnoMedia Inc",
"Innovent Systems, Inc.",
"Innolab Pte Ltd",
"Interphase Corporation",
"Ines GmbH",
"Interphase Corporation",
"Inviso, Inc.",
"Communications Supply Corporation (A division of WESCO)",
"Best Buy",
"CRE Technology Corporation",
"I-O Data Device Inc",
"Iomega",
"Inside Out Networks",
"i-O Display System",
"I/OTech Inc",
"IPC Corporation",
"Industrial Products Design, Inc.",
"Intelligent Platform Management Interface (IPMI) forum (Intel, HP, NEC, Dell)",
"IPM Industria Politecnica Meridionale SpA",
"Performance Technologies",
"IP Power Technologies GmbH",
"IP3 Technology Ltd.",
"Ithaca Peripherals",
"IPS, Inc. (Intellectual Property Solutions, Inc.)",
"International Power Technologies",
"IPWireless, Inc",
"IneoQuest Technologies, Inc",
"IMAGEQUEST Co., Ltd",
"Irdata",
"Symbol Technologies",
"Id3 Semiconductors",
"Insignia Solutions Inc",
"Interface Solutions",
"Isolation Systems",
"Image Stream Medical",
"IntreSource Systems Pte Ltd",
"INSIS Co., LTD.",
"ISS Inc",
"Intersolve Technologies",
"International Integrated Systems,Inc.(IISI)",
"Itausa Export North America",
"Intercom Inc",
"Internet Technology Corporation",
"Integrated Tech Express Inc",
"VanErum Group",
"ITK Telekommunikation AG",
"Inter-Tel",
"ITM inc.",
"The NTI Group",
"IT-PRO Consulting und Systemhaus GmbH",
"Infotronic America, Inc.",
"IDTECH",
"I&T Telecom.",
"integrated Technology Express Inc",
"ICSL",
"Intervoice Inc",
"Iiyama North America",
"Inlife-Handnet Co., Ltd.",
"Intevac Photonics Inc.",
"Icuiti Corporation",
"Intelliworxx, Inc.",
"Intertex Data AB",
"Shenzhen Inet Mobile Internet Technology Co., LTD",
"Astec Inc",
"Japan Aviation Electronics Industry, Limited",
"Janz Automationssysteme AG",
"Jaton Corporation",
"Carrera Computer Inc",
"Jace Tech Inc",
"Japan Display Inc.",
"Japan Digital Laboratory Co.,Ltd.",
"N-Vision",
"JET POWER TECHNOLOGY CO., LTD.",
"Jones Futurex Inc",
"University College",
"Jaeik Information & Communication Co., Ltd.",
"JVC KENWOOD Corporation",
"Micro Technical Company Ltd",
"JPC Technology Limited",
"Wallis Hamilton Industries",
"CNet Technical Inc",
"JS DigiTech, Inc",
"Jupiter Systems, Inc.",
"SANKEN ELECTRIC CO., LTD",
"JS Motorsports",
"jetway security micro,inc",
"Janich & Klass Computertechnik GmbH",
"Jupiter Systems",
"JVC",
"Video International Inc.",
"Jewell Instruments, LLC",
"JWSpencer & Co.",
"Jetway Information Co., Ltd",
"Karna",
"Kidboard Inc",
"Kobil Systems GmbH",
"Chunichi Denshi Co.,LTD.",
"Keycorp Ltd",
"KDE",
"Kodiak Tech",
"Korea Data Systems Co., Ltd.",
"KDS USA",
"KDDI Technology Corporation",
"Kyushu Electronics Systems Inc",
"Kontron Embedded Modules GmbH",
"Kesa Corporation",
"Kontron Europe GmbH",
"Key Tech Inc",
"SCD Tech",
"Komatsu Forest",
"Kofax Image Products",
"Klipsch Group, Inc",
"KEISOKU GIKEN Co.,Ltd.",
"Kionix, Inc.",
"KiSS Technology A/S",
"Mitsumi Company Ltd",
"KIMIN Electronics Co., Ltd.",
"Kensington Microware Ltd",
"Kramer Electronics Ltd. International",
"Konica corporation",
"Nutech Marketing PTL",
"Kobil Systems GmbH",
"Eastman Kodak Company",
"KOLTER ELECTRONIC",
"Kollmorgen Motion Technologies Group",
"KOUZIRO Co.,Ltd.",
"KOWA Company,LTD.",
"King Phoenix Company",
"TPK Holding Co., Ltd",
"Krell Industries Inc.",
"Kroma Telecom",
"Kroy LLC",
"Kinetic Systems Corporation",
"KUPA China Shenzhen Micro Technology Co., Ltd. Gold Institute",
"Karn Solutions Ltd.",
"King Tester Corporation",
"Kingston Tech Corporation",
"Takahata Electronics Co.,Ltd.",
"K-Tech",
"Kayser-Threde GmbH",
"Konica Technical Inc",
"Key Tronic Corporation",
"Katron Tech Inc",
"Kurta Corporation",
"Kvaser AB",
"KeyView",
"Kenwood Corporation",
"Kyocera Corporation",
"KYE Syst Corporation",
"Samsung Electronics America Inc",
"KEYENCE CORPORATION",
"K-Zone International co. Ltd.",
"K-Zone International",
"ACT Labs Ltd",
"LaCie",
"Microline",
"Laguna Systems",
"Sodeman Lancom Inc",
"LASAT Comm. A/S",
"Lava Computer MFG Inc",
"Lubosoft",
"LCI",
"Toshiba Matsushita Display Technology Co., Ltd",
"La Commande Electronique",
"Lite-On Communication Inc",
"Latitude Comm.",
"LEXICON",
"Longshine Electronics Company",
"Labcal Technologies",
"Laserdyne Technologies",
"LogiDataTech Electronic GmbH",
"Lectron Company Ltd",
"Long Engineering Design Inc",
"Legerity, Inc",
"Lenovo Group Limited",
"First International Computer Inc",
"Lexical Ltd",
"Logic Ltd",
"Logitech Inc",
"LG Semicom Company Ltd",
"Lasergraphics, Inc.",
"Lars Haagh ApS",
"Lung Hwa Electronics Company Ltd",
"Lighthouse Technologies Limited",
"Lenovo Beijing Co. Ltd.",
"Linked IP GmbH",
"Lithics Silicon Technology",
"Datalogic Corporation",
"Likom Technology Sdn. Bhd.",
"L-3 Communications",
"Lucent Technologies",
"Lexmark Int'l Inc",
"Leda Media Products",
"Laser Master",
"Land Computer Company Ltd",
"Link Tech Inc",
"Linear Systems Ltd.",
"LANETCO International",
"Lenovo",
"The Linux Foundation",
"Locamation B.V.",
"Loewe Opta GmbH",
"Logicode Technology Inc",
"Litelogic Operations Ltd",
"El-PUSK Co., Ltd.",
"Design Technology",
"DO NOT USE - LPL",
"LifeSize Communications",
"Intersil Corporation",
"Loughborough Sound Images",
"LSI Japan Company Ltd",
"Logical Solutions",
"LSI Systems Inc",
"Labtec Inc",
"Jongshine Tech Inc",
"Lucidity Technology Company Ltd",
"Litronic Inc",
"LTS Scale LLC",
"Leitch Technology International Inc.",
"Lightware, Inc",
"Lucent Technologies",
"Lumagen, Inc.",
"Luxxell Research Inc",
"LVI Low Vision International AB",
"Labway Corporation",
"Lightware Visual Engineering",
"Lanier Worldwide",
"LXCO Technologies AG",
"Luxeon",
"ELEA CardWare",
"Lightwell Company Ltd",
"MAC System Company Ltd",
"Xedia Corporation",
"Maestro Pty Ltd",
"MAG InnoVision",
"Mutoh America Inc",
"Meridian Audio Ltd",
"LGIC",
"Mass Inc.",
"Matsushita Electric Ind. Company Ltd",
"Rogen Tech Distribution Inc",
"Maynard Electronics",
"MAZeT GmbH",
"MBC",
"Microbus PLC",
"Marshall Electronics",
"Moreton Bay",
"American Nuclear Systems Inc",
"Micro Industries",
"McDATA Corporation",
"Metz-Werke GmbH & Co KG",
"Motorola Computer Group",
"Micronics Computers",
"Motorola Communications Israel",
"Metricom Inc",
"Micron Electronics Inc",
"Motion Computing Inc.",
"Magni Systems Inc",
"Mat's Computers",
"Marina Communicaitons",
"Micro Computer Systems",
"Microtec",
"Millson Custom Solutions Inc.",
"Media4 Inc",
"Midori Electronics",
"MODIS",
"MILDEF AB",
"Madge Networks",
"Micro Design Inc",
"Mediatek Corporation",
"Panasonic",
"Medar Inc",
"Micro Display Systems Inc",
"Magus Data Tech",
"MET Development Inc",
"MicroDatec GmbH",
"Microdyne Inc",
"Mega System Technologies Inc",
"Messeltronik Dresden GmbH",
"Mitsubishi Electric Engineering Co., Ltd.",
"Abeam Tech Ltd.",
"Panasonic Industry Company",
"Mac-Eight Co., LTD.",
"Mediaedge Corporation",
"Mitsubishi Electric Corporation",
"MEN Mikroelectronik Nueruberg GmbH",
"Meld Technology",
"Matelect Ltd.",
"Metheus Corporation",
"MPL AG, Elektronik-Unternehmen",
"MSC Vertriebs GmbH",
"MicroField Graphics Inc",
"Micro Firmware",
"MediaFire Corp.",
"Mega System Technologies, Inc.",
"Mentor Graphics Corporation",
"Schneider Electric S.A.",
"M-G Technology Ltd",
"Megatech R & D Company",
"Micom Communications Inc",
"miro Displays",
"Mitec Inc",
"Marconi Instruments Ltd",
"Mimio – A Newell Rubbermaid Company",
"Minicom Digital Signage",
"micronpc.com",
"Miro Computer Prod.",
"Modular Industrial Solutions Inc",
"MCM Industrial Technology GmbH",
"MicroImage Video Systems",
"MARANTZ JAPAN, INC.",
"MJS Designs",
"Media Tek Inc.",
"MK Seiko Co., Ltd.",
"MICROTEK Inc.",
"Trtheim Technology",
"Deep Video Imaging Ltd",
"Micrologica AG",
"McIntosh Laboratory Inc.",
"Millogic Ltd.",
"Millennium Engineering Inc",
"Mark Levinson",
"Magic Leap",
"Milestone EPE",
"Wanlida Group Co., Ltd.",
"Mylex Corporation",
"Micromedia AG",
"Micromed Biotecnologia Ltd",
"Minnesota Mining and Manufacturing",
"Multimax",
"Electronic Measurements",
"MiniMan Inc",
"MMS Electronics",
"Mini Micro Methods Ltd",
"Marseille, Inc.",
"Monorail Inc",
"Microcom",
"Modular Technology",
"Momentum Data Systems",
"Moses Corporation",
"Motorola UDS",
"M-Pact Inc",
"Mediatrix Peripherals Inc",
"Microlab",
"Maple Research Inst. Company Ltd",
"Mainpine Limited",
"mps Software GmbH",
"Micropix Technologies, Ltd.",
"MultiQ Products AB",
"Miranda Technologies Inc",
"Marconi Simulation & Ty-Coch Way Training",
"MicroDisplay Corporation",
"Maruko & Company Ltd",
"Miratel",
"Medikro Oy",
"Merging Technologies",
"Micro Systemation AB",
"Mouse Systems Corporation",
"Datenerfassungs- und Informationssysteme",
"M-Systems Flash Disk Pioneers",
"MSI GmbH",
"Microsoft",
"Microstep",
"Megasoft Inc",
"MicroSlate Inc.",
"Advanced Digital Systems",
"Mistral Solutions [P] Ltd.",
"MASPRO DENKOH Corp.",
"MS Telematica",
"motorola",
"Mosgi Corporation",
"Micomsoft Co., Ltd.",
"MicroTouch Systems Inc",
"Meta Watch Ltd",
"Media Technologies Ltd.",
"Mars-Tech Corporation",
"MindTech Display Co. Ltd",
"MediaTec GmbH",
"Micro-Tech Hearing Instruments",
"MaxCom Technical Inc",
"MicroTechnica Co.,Ltd.",
"Microtek International Inc.",
"Mitel Corporation",
"Motium",
"Mtron Storage Technology Co., Ltd.",
"Mitron computer Inc",
"Multi-Tech Systems",
"Mark of the Unicorn Inc",
"Matrox",
"Multi-Dimension Institute",
"Mainpine Limited",
"Microvitec PLC",
"Media Vision Inc",
"SOBO VISION",
"Meta Company",
"Microvision",
"COM 1",
"Multiwave Innovation Pte Ltd",
"mware",
"Microway Inc",
"MaxData Computer GmbH & Co.KG",
"Macronix Inc",
"Hitachi Maxell, Ltd.",
"Maxpeed Corporation",
"Maxtech Corporation",
"MaxVision Corporation",
"Monydata",
"Myriad Solutions Ltd",
"Micronyx Inc",
"Ncast Corporation",
"NAD Electronics",
"Nakano Engineering Co.,Ltd.",
"Network Alchemy",
"NaturalPoint Inc.",
"Navigation Corporation",
"Naxos Tecnologia",
"N*Able Technologies Inc",
"National Key Lab. on ISN",
"NingBo Bestwinning Technology CO., Ltd",
"Nixdorf Company",
"NCR Corporation",
"Norcent Technology, Inc.",
"NewCom Inc",
"NetComm Ltd",
"Najing CEC Panda FPD Technology CO. ltd",
"NCR Electronics",
"Northgate Computer Systems",
"NEC CustomTechnica, Ltd.",
"National DataComm Corporaiton",
"NDF Special Light Products B.V.",
"National Display Systems",
"Naitoh Densei CO., LTD.",
"Network Designers",
"Nokia Data",
"NEC Corporation",
"NEO TELECOM CO.,LTD.",
"INNES",
"Mettler Toledo",
"NEUROTEC - EMPRESA DE PESQUISA E DESENVOLVIMENTO EM BIOMEDICINA",
"Nexgen Mediatech Inc.,",
"BTC Korea Co., Ltd",
"Number Five Software",
"Network General",
"A D S Exports",
"Vinci Labs",
"National Instruments Corporation",
"Nissei Electric Company",
"Network Info Technology",
"Seanix Technology Inc",
"Next Level Communications",
"Navico, Inc.",
"Nokia Mobile Phones",
"Natural Micro System",
"NEC-Mitsubishi Electric Visual Systems Corporation",
"Neomagic",
"NNC",
"3NOD Digital Technology Co. Ltd.",
"NordicEye AB",
"North Invent A/S",
"Nokia Display Products",
"Norand Corporation",
"Not Limited Inc",
"Arvanics",
"Network Peripherals Inc",
"U.S. Naval Research Lab",
"Beijing Northern Radiantelecom Co.",
"Taugagreining hf",
"NeuroSky, Inc.",
"National Semiconductor Corporation",
"NISSEI ELECTRIC CO.,LTD",
"Nspire System Inc.",
"Newport Systems Solutions",
"Network Security Technology Co",
"NeoTech S.R.L",
"New Tech Int'l Company",
"National Transcomm. Ltd",
"Nuvoton Technology Corporation",
"N-trig Innovative Technologies, Inc.",
"Nits Technology Inc.",
"NTT Advanced Technology Corporation",
"Networth Inc",
"Netaccess Inc",
"NU Technology, Inc.",
"NU Inc.",
"NetVision Corporation",
"Nvidia",
"NuVision US, Inc.",
"Novell Inc",
"Navatek Engineering Corporation",
"NW Computer Engineering",
"NovaWeb Technologies Inc",
"Newisys, Inc.",
"NextCom K.K.",
"Nexgen",
"NXP Semiconductors bv.",
"Nexiq Technologies, Inc.",
"Technology Nexus Secure Open Systems AB",
"Nakayo Relecommunications, Inc.",
"Oak Tech Inc",
"Oasys Technology Company",
"Optibase Technologies",
"Macraigor Systems Inc",
"Olfan",
"Open Connect Solutions",
"ODME Inc.",
"Odrac",
"ORION ELECTRIC CO.,LTD",
"Optum Engineering Inc.",
"M-Labs Limited",
"Option Industrial Computers",
"Option International",
"Option International",
"OKI Electric Industrial Company Ltd",
"Olicom A/S",
"Olidata S.p.A.",
"Olivetti",
"Olitec S.A.",
"Olitec S.A.",
"OLYMPUS CORPORATION",
"OBJIX Multimedia Corporation",
"Omnitel",
"Omron Corporation",
"Oneac Corporation",
"ONKYO Corporation",
"OnLive, Inc",
"On Systems Inc",
"OPEN Networks Ltd",
"SOMELEC Z.I. Du Vert Galanta",
"OSRAM",
"Opcode Inc",
"D.N.S. Corporation",
"OPPO Digital, Inc.",
"OPTi Inc",
"Optivision Inc",
"Oksori Company Ltd",
"ORGA Kartensysteme GmbH",
"OSR Open Systems Resources, Inc.",
"ORION ELECTRIC CO., LTD.",
"OSAKA Micro Computer, Inc.",
"Optical Systems Design Pty Ltd",
"Open Stack, Inc.",
"OPTI-UPS Corporation",
"Oksori Company Ltd",
"outsidetheboxstuff.com",
"Orchid Technology",
"OmniTek",
"Optoma Corporation",
"OPTO22, Inc.",
"OUK Company Ltd",
"Oculus VR, Inc.",
"Mediacom Technologies Pte Ltd",
"Oxus Research S.A.",
"Shadow Systems",
"OZ Corporation",
"Tribe Computer Works Inc",
"Pacific Avionics Corporation",
"Promotion and Display Technology Ltd.",
"Many CNC System Co., Ltd.",
"Peter Antesberger Messtechnik",
"The Panda Project",
"Parallan Comp Inc",
"Pitney Bowes",
"Packard Bell Electronics",
"Packard Bell NEC",
"Pitney Bowes",
"Philips BU Add On Card",
"OCTAL S.A.",
"PowerCom Technology Company Ltd",
"First Industrial Computer Inc",
"Pioneer Computer Inc",
"PCBANK21",
"pentel.co.,ltd",
"PCM Systems Corporation",
"Performance Concepts Inc.,",
"Procomp USA Inc",
"TOSHIBA PERSONAL COMPUTER SYSTEM CORPRATION",
"PC-Tel Inc",
"Pacific CommWare Inc",
"PC Xperten",
"Psion Dacom Plc.",
"AT&T Paradyne",
"Pure Data Inc",
"PD Systems International Ltd",
"PDTS - Prozessdatentechnik und Systeme",
"Prodrive B.V.",
"POTRANS Electrical Corp.",
"Pegatron Corporation",
"PEI Electronics Inc",
"Primax Electric Ltd",
"Interactive Computer Products Inc",
"Peppercon AG",
"Perceptive Signal Technologies",
"Practical Electronic Tools",
"Telia ProSoft AB",
"PACSGEAR, Inc.",
"Paradigm Advanced Research Centre",
"propagamma kommunikation",
"Princeton Graphic Systems",
"Pijnenburg Beheer N.V.",
"Philips Medical Systems Boeblingen GmbH",
"DO NOT USE - PHI",
"Philips Consumer Electronics Company",
"Photonics Systems Inc.",
"Philips Communication Systems",
"Phylon Communications",
"Picturall Ltd.",
"Pacific Image Electronics Company Ltd",
"Prism, LLC",
"Pioneer Electronic Corporation",
"Pixie Tech Inc",
"Projecta",
"Projectiondesign AS",
"Pan Jit International Inc.",
"Acco UK Ltd.",
"Pro-Log Corporation",
"Panasonic Avionics Corporation",
"PROLINK Microsystems Corp.",
"PT Hartono Istana Teknologi",
"PLUS Vision Corp.",
"Parallax Graphics",
"Polycom Inc.",
"PMC Consumer Electronics Ltd",
"TDK USA Corporation",
"Point Multimedia System",
"Pabian Embedded Systems",
"Promate Electronic Co., Ltd.",
"Photomatrix",
"Microsoft",
"Panelview, Inc.",
"Microsoft",
"Planar Systems, Inc.",
"PanaScope",
"Phoenix Technologies, Ltd.",
"PolyComp (PTY) Ltd.",
"Perpetual Technologies, LLC",
"Portalis LC",
"Parrot",
"Phoenixtec Power Company Ltd",
"MEPhI",
"Practical Peripherals",
"Clinton Electronics Corp.",
"Purup Prepress AS",
"PicPro",
"Perceptive Pixel Inc.",
"Pixel Qi",
"PRO/AUTOMATION",
"PerComm",
"Praim S.R.L.",
"Digital Electronics Corporation",
"The Phoenix Research Group Inc",
"Priva Hortimation BV",
"Prometheus",
"Proteon",
"UEFI Forum",
"Leutron Vision",
"Parade Technologies, Ltd.",
"Proxima Corporation",
"Advanced Signal Processing Technologies",
"Philips Semiconductors",
"Peus-Systems GmbH",
"Practical Solutions Pte., Ltd.",
"PSI-Perceptive Solutions Inc",
"Perle Systems Limited",
"Prosum",
"Global Data SA",
"Prodea Systems Inc.",
"PAR Tech Inc.",
"PS Technology Corporation",
"Cipher Systems Inc",
"Pathlight Technology Inc",
"Promise Technology Inc",
"Pantel Inc",
"Plain Tree Systems Inc",
"DO NOT USE - PTW",
"Pulse-Eight Ltd",
"DO NOT USE - PVC",
"Proview Global Co., Ltd",
"Prime view international Co., Ltd",
"Penta Studiotechnik GmbH",
"Pixel Vision",
"Klos Technologies, Inc.",
"Pimax Tech. CO., LTD",
"Phoenix Contact",
"PIXELA CORPORATION",
"The Moving Pixel Company",
"Proxim Inc",
"QuakeCom Company Ltd",
"Metronics Inc",
"Quanta Computer Inc",
"Quick Corporation",
"Quadrant Components Inc",
"Qualcomm Inc",
"Quantum Data Incorporated",
"Quadram",
"Quanta Display Inc.",
"Padix Co., Inc.",
"Quickflex, Inc",
"Q-Logic",
"Chuomusen Co., Ltd.",
"Quantum Solutions, Inc.",
"Quantum 3D Inc",
"Questech Ltd",
"Quicknet Technologies Inc",
"Quantum",
"Qtronix Corporation",
"Quatographic AG",
"Questra Consulting",
"Quartics",
"Racore Computer Products Inc",
"Radisys Corporation",
"Rockwell Automation/Intecolor",
"Rancho Tech Inc",
"Raritan, Inc.",
"RAScom Inc",
"Rent-A-Tech",
"Raylar Design, Inc.",
"Parc d'Activite des Bellevues",
"Reach Technology Inc",
"RC International",
"Radio Consult SRL",
"Rockwell Collins",
"Rainbow Displays, Inc.",
"Tremon Enterprises Company Ltd",
"RADIODATA GmbH",
"Radius Inc",
"Real D",
"ReCom",
"Research Electronics Development Inc",
"Reflectivity, Inc.",
"Rehan Electronics Ltd.",
"Reliance Electric Ind Corporation",
"SCI Systems Inc.",
"Renesas Technology Corp.",
"ResMed Pty Ltd",
"Resonance Technology, Inc.",
"Revolution Display, Inc.",
"RATOC Systems, Inc.",
"RAFI GmbH & Co. KG",
"Redfox Technologies Inc.",
"RGB Spectrum",
"Robertson Geologging Ltd",
"RightHand Technologies",
"Rohm Company Ltd",
"Red Hat, Inc.",
"RICOH COMPANY, LTD.",
"Racal Interlan Inc",
"Rios Systems Company Ltd",
"Ritech Inc",
"Rivulet Communications",
"Roland Corporation",
"Advanced Engineering",
"Reakin Technolohy Corporation",
"MEPCO",
"RadioLAN Inc",
"Raritan Computer, Inc",
"Research Machines",
"Shenzhen Ramos Digital Technology Co., Ltd",
"Roper Mobile",
"Rainbow Technologies",
"Robust Electronics GmbH",
"Rohm Co., Ltd.",
"Rockwell International",
"Roper International Ltd",
"Rohde & Schwarz",
"RoomPro Technologies",
"R.P.T.Intergroups",
"Radicom Research Inc",
"PhotoTelesis",
"ADC-Centre",
"Rampage Systems Inc",
"Radiospire Networks, Inc.",
"R Squared",
"Zhong Shan City Richsound Electronic Industrial Ltd.",
"Rockwell Semiconductor Systems",
"Ross Video Ltd",
"Rapid Tech Corporation",
"Relia Technologies",
"Rancho Tech Inc",
"DO NOT USE - RTK",
"Realtek Semiconductor Company Ltd",
"Raintree Systems",
"RUNCO International",
"Ups Manufactoring s.r.l.",
"RSI Systems Inc",
"Realvision Inc",
"Reveal Computer Prod",
"Red Wing Corporation",
"Tectona SoftSolutions (P) Ltd.,",
"Rozsnyó, s.r.o.",
"Sanritz Automation Co.,Ltd.",
"Saab Aerotech",
"Sedlbauer",
"Sage Inc",
"Saitek Ltd",
"Samsung Electric Company",
"Sanyo Electric Co.,Ltd.",
"Stores Automated Systems Inc",
"Shuttle Tech",
"Shanghai Bell Telephone Equip Mfg Co",
"Softbed - Consulting & Development Ltd",
"SMART Technologies Inc.",
"SBS-or Industrial Computers GmbH",
"Senseboard Technologies AB",
"SeeCubic B.V.",
"SORD Computer Corporation",
"Sanyo Electric Company Ltd",
"Sun Corporation",
"Schlumberger Cards",
"System Craft",
"Sigmacom Co., Ltd.",
"SCM Microsystems Inc",
"Scanport, Inc.",
"SORCUS Computer GmbH",
"Scriptel Corporation",
"Systran Corporation",
"Nanomach Anstalt",
"Smart Card Technology",
"Socionext Inc.",
"SAT (Societe Anonyme)",
"Intrada-SDD Ltd",
"Sherwood Digital Electronics Corporation",
"SODIFF E&T CO., Ltd.",
"Communications Specialies, Inc.",
"Samtron Displays Inc",
"SAIT-Devlonics",
"SDR Systems",
"SunRiver Data System",
"Siemens AG",
"SDX Business Systems Ltd",
"Seanix Technology Inc.",
"system elektronik GmbH",
"Seiko Epson Corporation",
"SeeColor Corporation",
"DO NOT USE - SEG",
"Seitz & Associates Inc",
"Way2Call Communications",
"Samsung Electronics Company Ltd",
"Sencore",
"SEOS Ltd",
"SEP Eletronica Ltda.",
"Sony Ericsson Mobile Communications Inc.",
"Session Control LLC",
"SendTek Corporation",
"TORNADO Company",
"Mikroforum Ring 3",
"Spectragraphics Corporation",
"Sigma Designs, Inc.",
"Kansai Electric Company Ltd",
"Scan Group Ltd",
"Super Gate Technology Company Ltd",
"SAGEM",
"Logos Design A/S",
"Stargate Technology",
"Shanghai Guowei Science and Technology Co., Ltd.",
"Silicon Graphics Inc",
"Systec Computer GmbH",
"ShibaSoku Co., Ltd.",
"Soft & Hardware development Goldammer GmbH",
"Jiangsu Shinco Electronic Group Co., Ltd",
"Sharp Corporation",
"Digital Discovery",
"Shin Ho Tech",
"SIEMENS AG",
"Sanyo Electric Company Ltd",
"Sysmate Corporation",
"Seiko Instruments Information Devices Inc",
"Siemens",
"Sigma Designs Inc",
"Silicon Image, Inc.",
"Silicon Laboratories, Inc",
"S3 Inc",
"Singular Technology Co., Ltd.",
"Sirius Technologies Pty Ltd",
"Silicon Integrated Systems Corporation",
"Sitintel",
"Seiko Instruments USA Inc",
"Zuniq Data Corporation",
"Sejin Electron Inc",
"Schneider & Koch",
"Guangzhou Teclast Information Technology Limited",
"Samsung Electro-Mechanics Company Ltd",
"SKYDATA S.P.A.",
"Systeme Lauer GmbH&Co KG",
"Shlumberger Ltd",
"Syslogic Datentechnik AG",
"StarLeaf",
"Silicon Library Inc.",
"Symbios Logic Inc",
"Silitek Corporation",
"Solomon Technology Corporation",
"Schlumberger Technology Corporate",
"Schnick-Schnack-Systems GmbH",
"Salt Internatioinal Corp.",
"Specialix",
"SMART Modular Technologies",
"Schlumberger",
"Standard Microsystems Corporation",
"Sysmate Company",
"SpaceLabs Medical Inc",
"SMK CORPORATION",
"Sumitomo Metal Industries, Ltd.",
"Shark Multimedia Inc",
"STMicroelectronics",
"Simple Computing",
"B.& V. s.r.l.",
"Silicom Multimedia Systems Inc",
"Silcom Manufacturing Tech Inc",
"Sentronic International Corp.",
"Siemens Microdesign GmbH",
"S&K Electronics",
"SUNNY ELEKTRONIK",
"SINOSUN TECHNOLOGY CO., LTD",
"Siemens Nixdorf Info Systems",
"Cirtech (UK) Ltd",
"SuperNet Inc",
"Snell & Wilcox",
"Sonix Comm. Ltd",
"Sony",
"Santec Corporation",
"Silicon Optix Corporation",
"Solitron Technologies Inc",
"Sony",
"Sorcus Computer GmbH",
"Sotec Company Ltd",
"SOYO Group, Inc",
"SpinCore Technologies, Inc",
"SPEA Software AG",
"G&W Instruments GmbH",
"SPACE-I Co., Ltd.",
"SpeakerCraft",
"Smart Silicon Systems Pty Ltd",
"Sapience Corporation",
"pmns GmbH",
"Synopsys Inc",
"Sceptre Tech Inc",
"SIM2 Multimedia S.P.A.",
"Simplex Time Recorder Co.",
"Sequent Computer Systems Inc",
"Integrated Tech Express Inc",
"Setred",
"Surf Communication Solutions Ltd",
"Intuitive Surgical, Inc.",
"SR-Systems e.K.",
"SeeReal Technologies GmbH",
"Sierra Semiconductor Inc",
"FlightSafety International",
"Samsung Electronic Co.",
"S-S Technology Inc",
"Sankyo Seiki Mfg.co., Ltd",
"Shenzhen South-Top Computer Co., Ltd.",
"Spectrum Signal Proecessing Inc",
"S3 Inc",
"SystemSoft Corporation",
"ST Electronics Systems Assembly Pte Ltd",
"STB Systems Inc",
"STAC Electronics",
"STD Computer Inc",
"SII Ido-Tsushin Inc",
"Starflight Electronics",
"StereoGraphics Corp.",
"Semtech Corporation",
"Smart Tech Inc",
"SANTAK CORP.",
"SigmaTel Inc",
"SGS Thomson Microelectronics",
"Samsung Electronics America",
"Stollmann E+V GmbH",
"StreamPlay Ltd",
"Synthetel Corporation",
"Starlight Networks Inc",
"SITECSYSTEM CO., LTD.",
"Star Paging Telecom Tech (Shenzhen) Co. Ltd.",
"Sentelic Corporation",
"Starwin Inc.",
"ST-Ericsson",
"SDS Technologies",
"Subspace Comm. Inc",
"Summagraphics Corporation",
"Sun Electronics Corporation",
"Supra Corporation",
"Surenam Computer Corporation",
"SGEG",
"Intellix Corp.",
"SVD Computer",
"Sun Microsystems",
"Sensics, Inc.",
"SVSI",
"SEVIT Co., Ltd.",
"Software Café",
"Sierra Wireless Inc.",
"Sharedware Ltd",
"Guangzhou Shirui Electronics Co., Ltd.",
"Static",
"Software Technologies Group,Inc.",
"Syntax-Brillian",
"Silex technology, Inc.",
"SELEX GALILEO",
"SolutionInside",
"SHARP TAKAYA ELECTRONIC INDUSTRY CO.,LTD.",
"Sysmic",
"SY Electronics Ltd",
"Stryker Communications",
"Sylvania Computer Products",
"Symicron Computer Communications Ltd.",
"Synaptics Inc",
"SYPRO Co Ltd",
"Sysgration Ltd",
"Seyeon Tech Company Ltd",
"SYVAX Inc",
"Prime Systems, Inc.",
"Shenzhen MTC Co., Ltd",
"Tandberg",
"Todos Data System AB",
"Teles AG",
"Toshiba America Info Systems Inc",
"Tamura Seisakusyo Ltd",
"Taskit Rechnertechnik GmbH",
"Teleliaison Inc",
"Thales Avionics",
"Taxan (Europe) Ltd",
"Triple S Engineering Inc",
"Turbo Communication, Inc",
"Turtle Beach System",
"Tandon Corporation",
"Taicom Data Systems Co., Ltd.",
"Century Corporation",
"Televic Conference",
"Interaction Systems, Inc",
"Tulip Computers Int'l B.V.",
"TEAC America Inc",
"Technical Concepts Ltd",
"3Com Corporation",
"Tecnetics (PTY) Ltd",
"Thomas-Conrad Corporation",
"Thomson Consumer Electronics",
"Tatung Company of America Inc",
"Telecom Technology Centre Co. Ltd.",
"FREEMARS Heavy Industries",
"Teradici",
"Tandberg Data Display AS",
"Six15 Technologies",
"Tandem Computer Europe Inc",
"3D Perception",
"Tri-Data Systems Inc",
"TDT",
"TDVision Systems, Inc.",
"Tandy Electronics",
"TEAC System Corporation",
"Tecmar Inc",
"Tektronix Inc",
"Promotion and Display Technology Ltd.",
"TerraTec Electronic GmbH",
"TETRADYNE CO., LTD.",
"Tech Source Inc.",
"Toshiba Global Commerce Solutions, Inc.",
"TriGem Computer Inc",
"TriGem Computer,Inc.",
"Torus Systems Ltd",
"Grass Valley Germany GmbH",
"Thundercom Holdings Sdn. Bhd.",
"Trigem KinfoComm",
"Technical Illusions Inc.",
"TIPTEL AG",
"OOO Technoinvest",
"Tixi.Com GmbH",
"Taiko Electric Works.LTD",
"Tek Gear",
"Teknor Microsystem Inc",
"TouchKo, Inc.",
"TimeKeeping Systems, Inc.",
"Ferrari Electronic GmbH",
"Telindus",
"Zhejiang Tianle Digital Electric Co., Ltd.",
"Teleforce.,co,ltd",
"TOSHIBA TELI CORPORATION",
"Telelink AG",
"Thinklogical",
"Techlogix Networx",
"Teleste Educational OY",
"Dai Telecom S.p.A.",
"S3 Inc",
"Telxon Corporation",
"Techmedia Computer Systems Corporation",
"AT&T Microelectronics",
"Texas Microsystem",
"Time Management, Inc.",
"Taicom International Inc",
"Trident Microsystems Ltd",
"T-Metrics Inc.",
"Thermotrex Corporation",
"TNC Industrial Company Ltd",
"DO NOT USE - TNJ",
"TECNIMAGEN SA",
"Tennyson Tech Pty Ltd",
"TOEI Electronics Co., Ltd.",
"The OPEN Group",
"TCL Corporation",
"Ceton Corporation",
"TONNA",
"Orion Communications Co., Ltd.",
"Toshiba Corporation",
"Touchstone Technology",
"Touch Panel Systems Corporation",
"Times (Shanghai) Computer Co., Ltd.",
"Technology Power Enterprises Inc",
"Junnila",
"TOPRE CORPORATION",
"Topro Technology Inc",
"Teleprocessing Systeme GmbH",
"Thruput Ltd",
"Top Victory Electronics ( Fujian ) Company Ltd",
"Ypoaz Systems Inc",
"TriTech Microelectronics International",
"Triumph Board a.s.",
"Trioc AB",
"Trident Microsystem Inc",
"Tremetrics",
"Tricord Systems",
"Royal Information",
"Tekram Technology Company Ltd",
"Datacommunicatie Tron B.V.",
"TRAPEZE GROUP",
"Torus Systems Ltd",
"Tritec Electronic AG",
"Aashima Technology B.V.",
"Trivisio Prototyping GmbH",
"Trex Enterprises",
"Toshiba America Info Systems Inc",
"Sanyo Electric Company Ltd",
"TechniSat Digital GmbH",
"Tottori Sanyo Electric",
"Racal-Airtech Software Forge Ltd",
"The Software Group Ltd",
"ELAN MICROELECTRONICS CORPORATION",
"TeleVideo Systems",
"Tottori SANYO Electric Co., Ltd.",
"U.S. Navy",
"Transtream Inc",
"TRANSVIDEO",
"TouchSystems",
"Topson Technology Co., Ltd.",
"National Semiconductor Japan Ltd",
"Telecommunications Techniques Corporation",
"TTE, Inc.",
"Trenton Terminals Inc",
"Totoku Electric Company Ltd",
"2-Tel B.V",
"Toshiba Corporation",
"TechnoTrend Systemtechnik GmbH",
"Taitex Corporation",
"TRIDELITY Display Solutions GmbH",
"T+A elektroakustik GmbH",
"Tut Systems",
"Tecnovision",
"Truevision",
"Total Vision LTD",
"Taiwan Video & Monitor Corporation",
"TV One Ltd",
"TV Interactive Corporation",
"TVS Electronics Limited",
"TV1 GmbH",
"Tidewater Association",
"Kontron Electronik",
"Twinhead International Corporation",
"Easytel oy",
"TOWITOKO electronics GmbH",
"TEKWorx Limited",
"Trixel Ltd",
"Texas Insturments",
"Textron Defense System",
"Tyan Computer Corporation",
"Ultima Associates Pte Ltd",
"Ungermann-Bass Inc",
"Ubinetics Ltd.",
"Canonical Ltd.",
"Uniden Corporation",
"Ultima Electronics Corporation",
"Elitegroup Computer Systems Company Ltd",
"Universal Electronics Inc",
"Universal Empowering Technologies",
"UNIGRAF-USA",
"UFO Systems Inc",
"XOCECO",
"Uniform Industrial Corporation",
"Ueda Japan Radio Co., Ltd.",
"Ultra Network Tech",
"United Microelectr Corporation",
"Umezawa Giken Co.,Ltd",
"Universal Multimedia",
"UltiMachine",
"Unisys DSD",
"Unisys Corporation",
"Unisys Corporation",
"DO NOT USE - UND",
"DO NOT USE - UNE",
"DO NOT USE - UNF",
"Uniform Industry Corp.",
"Unisys Corporation",
"Unisys Corporation",
"Unitop",
"Unisys Corporation",
"Unisys Corporation",
"Unicate",
"UPPI",
"Systems Enhancement",
"Video Computer S.p.A.",
"Utimaco Safeware AG",
"U.S. Digital Corporation",
"U. S. Electronics Inc.",
"Universal Scientific Industrial Co., Ltd.",
"U.S. Robotics Inc",
"Up to Date Tech",
"Uniwill Computer Corp.",
"Vaddio, LLC",
"VAIO Corporation",
"Valence Computing Corporation",
"Varian Australia Pty Ltd",
"VBrick Systems Inc.",
"Valley Board Ltda",
"Virtual Computer Corporation",
"VistaCom Inc",
"Victor Company of Japan, Limited",
"Vector Magnetics, LLC",
"VCONEX",
"Victor Data Systems",
"VDC Display Systems",
"Vadem",
"Video & Display Oriented Corporation",
"Vidisys GmbH & Company",
"Viditec, Inc.",
"Vector Informatik GmbH",
"Vektrex",
"Vestel Elektronik Sanayi ve Ticaret A. S.",
"VeriFone Inc",
"Macrocad Development Inc.",
"VIA Tech Inc",
"Tatung UK Ltd",
"Victron B.V.",
"Ingram Macrotron Germany",
"Viking Connectors",
"Via Mons Ltd.",
"Vine Micros Ltd",
"Visual Interface, Inc",
"Visioneer",
"Visitech AS",
"VIZIO, Inc",
"ValleyBoard Ltda.",
"VersaLogic Corporation",
"Vislink International Ltd",
"VideoLan Technologies",
"Valve Corporation",
"Vermont Microsystems",
"Vine Micros Limited",
"VMware Inc.,",
"Vinca Corporation",
"MaxData Computer AG",
"Video Products Inc",
"Best Buy",
"VPixx Technologies Inc.",
"Vision Quest",
"Virtual Resources Corporation",
"VRmagic Holding AG",
"ViewSonic Corporation",
"3M",
"VideoServer",
"Ingram Macrotron",
"Vision Systems GmbH",
"V-Star Electronics Inc.",
"Videotechnik Breithaupt",
"VTel Corporation",
"Voice Technologies Group Inc",
"VLSI Tech Inc",
"Viewteck Co., Ltd.",
"Vivid Technology Pte Ltd",
"Miltope Corporation",
"VIDEOTRON CORP.",
"VTech Computers Ltd",
"VATIV Technologies",
"Vestax Corporation",
"Vutrix (UK) Ltd",
"Vweb Corp.",
"Wacom Tech",
"Wave Access",
"DO NOT USE - WAN",
"Wavephore",
"MicroSoftWare",
"WB Systemtechnik GmbH",
"Wisecom Inc",
"Woodwind Communications Systems Inc",
"Western Digital",
"Westinghouse Digital Electronics",
"WebGear Inc",
"Winbond Electronics Corporation",
"W-DEV",
"WEY Design AG",
"Whistle Communications",
"Innoware Inc",
"WIPRO Information Technology Ltd",
"Wintop Technology Inc",
"Wipro Infotech",
"Uni-Take Int'l Inc.",
"Wildfire Communications Inc",
"Wolfson Microelectronics Ltd",
"Westermo Teleindustri AB",
"Winmate Communication Inc",
"WillNet Inc.",
"Winnov L.P.",
"Wincor Nixdorf International GmbH",
"Matsushita Communication Industrial Co., Ltd.",
"Wearnes Peripherals International (Pte) Ltd",
"WiNRADiO Communications",
"CIS Technology Inc",
"Wireless And Smart Products Inc.",
"Wistron Corporation",
"ACC Microelectronics",
"WorkStation Tech",
"Wearnes Thakral Pte",
"Restek Electric Company Ltd",
"Wave Systems Corporation",
"WolfVision GmbH",
"Wipotec Wiege- und Positioniersysteme GmbH",
"World Wide Video, Inc.",
"Woxter Technology Co. Ltd",
"Myse Technology",
"Wooyoung Image & Information Co.,Ltd.",
"XAC Automation Corp",
"Alpha Data",
"XDM Ltd.",
"DO NOT USE - XER",
"Jan Strapko - FOTO",
"EXFO Electro Optical Engineering",
"Xinex Networks Inc",
"Xiotech Corporation",
"Xirocm Inc",
"Xitel Pty ltd",
"Xilinx, Inc.",
"C3PO S.L.",
"XN Technologies, Inc.",
"DO NOT USE - XOC",
"SHANGHAI SVA-DAV ELECTRONICS CO., LTD",
"Xircom Inc",
"XORO ELECTRONICS (CHENGDU) LIMITED",
"Xscreen AS",
"XS Technologies Inc",
"XSYS",
"Icuiti Corporation",
"X2E GmbH",
"Crystal Computer",
"X-10 (USA) Inc",
"Xycotec Computer GmbH",
"Shenzhen Zhuona Technology Co., Ltd.",
"Y-E Data Inc",
"Yokogawa Electric Corporation",
"Exacom SA",
"Yamaha Corporation",
"American Biometric Company",
"Zandar Technologies plc",
"Zefiro Acoustics",
"Zazzle Technologies",
"Zebra Technologies International, LLC",
"Zebax Technologies",
"ZeitControl cardsystems GmbH",
"Zenith Data Systems",
"ZENIC Inc.",
"Zenith Data Systems",
"Nationz Technologies Inc.",
"HangZhou ZMCHIVIN",
"Zalman Tech Co., Ltd.",
"Z Microsystems",
"Zetinet Inc",
"Znyx Adv. Systems",
"Zowie Intertainment, Inc",
"Zoran Corporation",
"Zenith Data Systems",
"ZyDAS Technology Corporation",
"ZTE Corporation",
"Zoom Telephonics Inc",
"ZT Group Int'l Inc.",
"Z3 Technology",
"Shenzhen Zowee Technology Co., LTD",
"Zydacron Inc",
"Zypcom Inc",
"Zytex Computers",
"Zyxel",
"Boca Research Inc",
"Inovatec S.p.A.",

};

/* pnp_name, given a key of three charaters (null terminator optional; any
extra bytes are ignored), looks up the matching name and returns a pointer to
it, or NULL if not found. The returned pointer, if not NULL, is to a
null-terminated read-only string that does not need to be freed. The name is
guarenteed to fit into a buffer of 128 bytes, including at least one null
terminator. */
const char *pnp_name(const char *key)
{
    /* binary search of pnp_keys */
    size_t start = 0;
    size_t pos = num_ids / 2;
    size_t end = num_ids;
    
    while ((pos >= start) && (pos < end))
    {
        int c = memcmp(key, &pnp_keys[3 * pos], 3);
        if (c == 0) { return pnp_names[pos]; }
        if (c < 0)  { end = pos; }
        if (c > 0)  { start = pos + 1; }
        
        pos = start + ((end - start) / 2);
    }
    
    return NULL;
}

